version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: task-manager-db
    environment:
      POSTGRES_DB: taskmanagerdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"